-- Add first-class news categories for filtering and navigation.
ALTER TABLE news ADD COLUMN category TEXT DEFAULT 'other';

UPDATE news
SET category = CASE
  WHEN lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%coindesk%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%cointelegraph%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%decrypt%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%crypto.news%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%blockchain.news%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%panews%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%bitcoin%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%ethereum%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%crypto%'
    OR lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%blockchain%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%比特币%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%以太坊%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%加密%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%区块链%'
    THEN 'crypto'
  WHEN lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%kitco%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%gold%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%silver%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%黄金%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%白银%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%贵金属%'
    THEN 'precious_metals'
  WHEN lower(coalesce(source, '') || ' ' || coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%fxstreet%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%forex%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%currency%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%eur/usd%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%usd/cny%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%外汇%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%汇率%'
    THEN 'forex'
  WHEN lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%oil%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%crude%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%copper%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%commodity%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%原油%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%石油%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%大宗商品%'
    THEN 'commodities'
  WHEN lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%stock%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%shares%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%earnings%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%nasdaq%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%s&p%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%股票%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%股市%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%美股%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%财报%'
    THEN 'equity'
  WHEN lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%fed%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%inflation%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%cpi%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%gdp%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%treasury%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%economy%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%policy%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%politics%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%government%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%trade%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%美联储%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%通胀%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%经济%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%利率%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%政策%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%政治%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%政府%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%贸易%'
    THEN 'macro'
  WHEN lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%hack%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%lawsuit%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%bankruptcy%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%risk%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%war%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%conflict%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%geopolitical%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%sanction%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%tariff%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%election%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%风险%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%破产%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%诉讼%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%战争%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%冲突%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%地缘%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%制裁%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%关税%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%选举%'
    THEN 'risk'
  WHEN lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%strategy%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%analysis%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%forecast%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%策略%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%分析%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%预测%'
    THEN 'strategy'
  WHEN lower(coalesce(source, '')) LIKE '%yahoo finance%'
    OR lower(coalesce(title, '') || ' ' || coalesce(summary, '')) LIKE '%market%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%市场%'
    OR coalesce(title, '') || ' ' || coalesce(summary, '') LIKE '%行情%'
    THEN 'markets'
  ELSE 'other'
END
WHERE category IS NULL OR category = '' OR category = 'other';

CREATE INDEX IF NOT EXISTS idx_news_category_published_at ON news(category, published_at DESC);


